# Generated by Django 2.1 on 2018-08-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default='Joe', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default='Blow', max_length=50),
        ),
    ]
