# Generated by Django 2.1 on 2018-08-21 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0003_auto_20180819_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxLengthValidator(9999999999)]),
        ),
    ]
