# Generated by Django 2.1 on 2018-08-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0005_animal_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'DOG'), ('cat', 'CAT'), ('other', 'OTHER')], default='dog', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(choices=[('6 months', '6 months'), ('1 YEAR', '1 YEAR'), ('2-5 YEARS', '2-5 YEARS'), ('5-10 YEARS', '5-10 YEARS'), ('10 YEARS OR OLDER', '10 YEARS OR OLDER')], max_length=20),
        ),
    ]
