# Generated by Django 2.1 on 2018-08-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0006_auto_20180821_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='current_pets_total',
        ),
    ]
