# Generated by Django 2.1 on 2018-08-24 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0008_remove_application_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pets_cats',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='pets_other',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
