# Generated by Django 2.1 on 2018-08-11 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20180810_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentvote', to='vote.Comment'),
        ),
        migrations.AlterField(
            model_name='imagevote',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagevote', to='vote.Image'),
        ),
    ]
