# Generated by Django 2.1 on 2018-08-19 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20180819_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerJobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('Alexandria', 'Alexandria Location'), ('Springfield', 'Springfield Location'), ('Arlington', 'Arlington Location'), ('Woodbridge', 'Woodbridge Location'), ('Falls Church', 'Falls Church Location')], max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('hours', models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
