# Generated by Django 2.1 on 2018-08-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_volunteerjobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolunteerJobs',
            new_name='VolunteerJob',
        ),
    ]
