# Generated by Django 2.1 on 2018-08-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_auto_20180819_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerJob',
        ),
    ]
