# Generated by Django 2.1 on 2018-08-19 19:10

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('about_you', models.TextField(validators=[django.core.validators.MaxLengthValidator(250), django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('contact_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxLengthValidator(9999999999)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('Alexandria', 'Alexandria Location'), ('Springfield', 'Springfield Location'), ('Arlington', 'Arlington Location'), ('Woodbridge', 'Woodbridge Location'), ('Falls Church', 'Falls Church Location')], max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('hours', models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
