# Generated by Django 2.1 on 2018-08-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=models.SlugField(help_text='Cannot contain spaces', primary_key=True, serialize=False),
        ),
    ]
